import Head from 'next/head'
import { Categories, PostCard, PostWidget } from '../components';
import { getPosts } from '../services';

export default function Home({ posts }) {
  return (
    <div className='container mx-auto lg:px-10 mb-8 md:px-2 px-1'>
      <Head>
        <title>Blogger</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-3 lg:top-8">
            <div className="lg:sticky relative top-3 lg:top-8">
              <PostWidget />
              <Categories />
            </div>
          </div>
        </div>
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, idx) => <PostCard key={idx} post={post.node} />)}
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = await getPosts() || [];
  return {
    props: { posts }
  }
}
